theme: jekyll-theme-cayman
plugins:
- jekyll-remote-theme 
title: Cubo de leds 4x4x4
description: Proyecto final CUBO LED del curso "Integración de Sistemas y Arquitecturas"
show_downloads: true
